name: outdoorsy
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - numpy=1.21.2
  - pandas=1.3.5
  - pip=21.2.4
  - python=3.9.7
  - scikit-learn=1.0.2
  - pip:
    - matplotlib==3.5.1
    - plotly==5.5.0
